FROM trevorj/ubuntu-salt-minion:latest

# Set minion ID
ENV MINION_ID ${SALT_MINION_ID:-$APP_NAME}.${BUILD_ENV:-dev}
ONBUILD RUN /opt/salty-docker/set-minion-id

# Add salt directories
ONBUILD ADD pillar /app/pillar
ONBUILD ADD salt /app/salt
ONBUILD ADD states /app/states

# Add python project files
ONBUILD ADD setup.py /app/setup.py
ONBUILD ADD image/build.sh /app/image/build.sh
ONBUILD RUN APP_ENV=build DOCKER_BUILD=1 /app/image/build.sh

ONBUILD ADD bin /app/bin
ONBUILD ADD image /app/image

WORKDIR /app

ENV APP_ENV dev
VOLUME /data

ENTRYPOINT ["/app/bin/entrypoint"]
CMD ["shell"]
